/**
* @file client-meteor.js
* @description Meteor runtime file that imports the Rspack bundle
* --------------------------------------------------------------------------
* ☄️ Meteor Client App (Development)
* --------------------------------------------------------------------------
* • [   client-entry.js ] ──▶ [   client-rspack.js ] ──▶ [■ client-meteor.js ]
*
* This file overrides the corresponding `meteor.mainModule.client` entry in
* package.json. Meteor loads it at runtime, and it imports the Rspack
* bundle (`client-rspack.js`) so the application executes using the build
* produced by Rspack.
*
* ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
* These files also act as a cache: they can be safely removed and will be
* regenerated on the next build. They should be ignored in IDE suggestions
* and version control.
*/

/* No link to ⚡ Rspack Client App as served by HMR server */

/* Polyfill globalThis.module, exports & module for legacy */
if (typeof globalThis !== 'undefined') {
  if (typeof globalThis.module === 'undefined') {
    globalThis.module = { exports: {} };
  }
  if (typeof globalThis.exports === 'undefined') {
    globalThis.exports = globalThis.module.exports;
  }
}
if (typeof window.module === 'undefined') {
  window.module = { exports: {} };
}

function lazyExternalImports1() {
  require('react');
  require('meteor/meteor');
  require('react-dom');
  require('meteor/mongo');
  require('meteor/react-meteor-data');
}
