/*!
 * /**
 * * @file server-rspack.js
 * * @description No code generated
 * * --------------------------------------------------------------------------
 * * ⚡ Rspack Server App (Development)
 * * --------------------------------------------------------------------------
 * * • [   server-entry.js ] ──▶ [■ server-rspack.js ] ──▶ [   server-meteor.js ]
 * *
 * * This file is empty because `meteor.mainModule.server` is not set in package.json.
 * *
 * * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * * These files also act as a cache: they can be safely removed and will be
 * * regenerated on the next build. They should be ignored in IDE suggestions
 * * and version control.
 * * /
 *
 *
 *
 */
(() => {
var __webpack_modules__ = ({
"./bot/seed.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  runSeed: () => (runSeed)
});
/* import */ var meteor_accounts_base__rspack_import_0 = __webpack_require__("meteor/accounts-base");
/* import */ var meteor_accounts_base__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_accounts_base__rspack_import_0);
/* import */ var meteor_meteor__rspack_import_1 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_1);
/* import */ var _imports_api_slots_slots_js__rspack_import_2 = __webpack_require__("./imports/api/slots/slots.js");
/* import */ var _imports_api_appointments_appointments_js__rspack_import_3 = __webpack_require__("./imports/api/appointments/appointments.js");
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}
function _define_property(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
function _object_spread(target) {
    for(var i = 1; i < arguments.length; i++){
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);
        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function(sym) {
                return Object.getOwnPropertyDescriptor(source, sym).enumerable;
            }));
        }
        ownKeys.forEach(function(key) {
            _define_property(target, key, source[key]);
        });
    }
    return target;
}




const CLIENTES = [
    {
        email: 'juan@test.com',
        name: 'Juan Pérez',
        phone: '0991111111',
        patron: {
            diasFavoritos: [
                5,
                6
            ],
            horasFavoritas: [
                '09:00',
                '10:00'
            ],
            frecuencia: 0.8
        }
    },
    {
        email: 'maria@test.com',
        name: 'María García',
        phone: '0992222222',
        patron: {
            diasFavoritos: [
                3,
                4
            ],
            horasFavoritas: [
                '14:00',
                '15:00'
            ],
            frecuencia: 0.6
        }
    },
    {
        email: 'andres@test.com',
        name: 'Andrés Torres',
        phone: '0993333333',
        patron: {
            diasFavoritos: [
                1,
                2
            ],
            horasFavoritas: [
                '11:00',
                '12:00'
            ],
            frecuencia: 0.4
        }
    },
    {
        email: 'sofia@test.com',
        name: 'Sofía Ruiz',
        phone: '0994444444',
        patron: {
            diasFavoritos: [
                5,
                6
            ],
            horasFavoritas: [
                '16:00',
                '17:00'
            ],
            frecuencia: 0.75
        }
    },
    {
        email: 'diego@test.com',
        name: 'Diego Castro',
        phone: '0995555555',
        patron: {
            diasFavoritos: [
                4,
                5
            ],
            horasFavoritas: [
                '10:00',
                '11:00'
            ],
            frecuencia: 0.65
        }
    },
    {
        email: 'lucia@test.com',
        name: 'Lucía Mora',
        phone: '0996666666',
        patron: {
            diasFavoritos: [
                2,
                3
            ],
            horasFavoritas: [
                '09:00',
                '14:00'
            ],
            frecuencia: 0.5
        }
    },
    {
        email: 'carlosc@test.com',
        name: 'Carlos Vega',
        phone: '0997777777',
        patron: {
            diasFavoritos: [
                6
            ],
            horasFavoritas: [
                '10:00',
                '11:00',
                '12:00'
            ],
            frecuencia: 0.9
        }
    },
    {
        email: 'ana@test.com',
        name: 'Ana Flores',
        phone: '0998888888',
        patron: {
            diasFavoritos: [
                1,
                3,
                5
            ],
            horasFavoritas: [
                '15:00',
                '16:00'
            ],
            frecuencia: 0.55
        }
    }
];
const BARBEROS = [
    {
        email: 'carlos@barberturn.com',
        name: 'Carlos Mendoza',
        horario: {
            dias: [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            horas: [
                '09:00',
                '10:00',
                '11:00',
                '12:00',
                '14:00',
                '15:00',
                '16:00',
                '17:00'
            ]
        }
    },
    {
        email: 'luis@barberturn.com',
        name: 'Luis Paredes',
        horario: {
            dias: [
                1,
                2,
                3,
                4,
                5
            ],
            horas: [
                '09:00',
                '10:00',
                '11:00',
                '14:00',
                '15:00',
                '16:00'
            ]
        }
    },
    {
        email: 'pedro@barberturn.com',
        name: 'Pedro Vásquez',
        horario: {
            dias: [
                3,
                4,
                5,
                6
            ],
            horas: [
                '10:00',
                '11:00',
                '12:00',
                '15:00',
                '16:00',
                '17:00'
            ]
        }
    }
];
const DEMANDA_DIA = {
    1: 0.25,
    2: 0.35,
    3: 0.55,
    4: 0.60,
    5: 0.85,
    6: 0.90
};
const fechaUTC5 = (date)=>{
    const d = new Date(date);
    d.setUTCHours(5, 0, 0, 0);
    return d;
};
const calcProb = (cliente, diaSemana, hora)=>{
    const { diasFavoritos, horasFavoritas, frecuencia } = cliente.patron;
    const esDiaFav = diasFavoritos.includes(diaSemana) ? 1.3 : 0.7;
    const esHoraFav = horasFavoritas.includes(hora) ? 1.4 : 0.6;
    const demandaBase = DEMANDA_DIA[diaSemana] || 0.5;
    const ruido = 0.85 + Math.random() * 0.3;
    return Math.min(frecuencia * esDiaFav * esHoraFav * demandaBase * ruido, 1);
};
const decidirStatus = (prob)=>{
    if (Math.random() > prob) return null;
    const r = Math.random();
    if (r < 0.75) return 'confirmed';
    if (r < 0.90) return 'cancelled';
    return 'pending';
};
const runSeed = ()=>_async_to_generator(function*() {
        console.log('🌱 Iniciando seed con comportamiento aleatorio realista...');
        // 1. Crear barberos
        const barberoIds = [];
        for (const b of BARBEROS){
            var _this;
            let userId = (_this = yield meteor_meteor__rspack_import_1.Meteor.users.findOneAsync({
                'emails.address': b.email
            })) === null || _this === void 0 ? void 0 : _this._id;
            if (!userId) {
                userId = yield meteor_accounts_base__rspack_import_0.Accounts.createUser({
                    email: b.email,
                    password: '123456',
                    profile: {
                        name: b.name,
                        role: 'barbero'
                    }
                });
                console.log(`💈 Barbero creado: ${b.name}`);
            }
            barberoIds.push(_object_spread({
                userId
            }, b));
        }
        // 2. Crear clientes
        const clienteIds = [];
        for (const c of CLIENTES){
            var _this1;
            let userId = (_this1 = yield meteor_meteor__rspack_import_1.Meteor.users.findOneAsync({
                'emails.address': c.email
            })) === null || _this1 === void 0 ? void 0 : _this1._id;
            if (!userId) {
                userId = yield meteor_accounts_base__rspack_import_0.Accounts.createUser({
                    email: c.email,
                    password: '123456',
                    profile: {
                        name: c.name,
                        role: 'cliente',
                        phone: c.phone
                    }
                });
            }
            clienteIds.push(_object_spread({
                userId
            }, c));
        }
        // 3. Generar 8 semanas de histórico
        const hoy = new Date();
        let totalSlots = 0, totalReservas = 0, totalCancelados = 0;
        for(let semana = 8; semana >= 1; semana--){
            for(let offsetDia = 0; offsetDia < 7; offsetDia++){
                const fecha = new Date(hoy);
                fecha.setDate(hoy.getDate() - semana * 7 + offsetDia);
                const diaSemana = fecha.getDay();
                if (diaSemana === 0) continue;
                const fechaDB = fechaUTC5(fecha);
                for (const barbero of barberoIds){
                    if (!barbero.horario.dias.includes(diaSemana)) continue;
                    if (Math.random() < 0.05) continue;
                    for (const hora of barbero.horario.horas){
                        if (Math.random() < 0.10) continue;
                        const existe = yield _imports_api_slots_slots_js__rspack_import_2.Slots.findOneAsync({
                            barberId: barbero.userId,
                            date: fechaDB,
                            hour: hora
                        });
                        if (existe) continue;
                        const slotId = yield _imports_api_slots_slots_js__rspack_import_2.Slots.insertAsync({
                            barberId: barbero.userId,
                            date: fechaDB,
                            hour: hora,
                            isAvailable: true,
                            appointmentId: null,
                            createdAt: fecha
                        });
                        totalSlots++;
                        const clientesMezclados = [
                            ...clienteIds
                        ].sort(()=>Math.random() - 0.5);
                        let slotOcupado = false;
                        for (const cliente of clientesMezclados){
                            if (slotOcupado) break;
                            const prob = calcProb(cliente, diaSemana, hora);
                            const status = decidirStatus(prob);
                            if (status) {
                                const appointmentId = yield _imports_api_appointments_appointments_js__rspack_import_3.Appointments.insertAsync({
                                    slotId,
                                    clientName: cliente.name,
                                    clientPhone: cliente.phone,
                                    barberId: barbero.userId,
                                    date: fechaDB,
                                    hour: hora,
                                    status,
                                    createdAt: fecha
                                });
                                yield _imports_api_slots_slots_js__rspack_import_2.Slots.updateAsync(slotId, {
                                    $set: {
                                        isAvailable: false,
                                        appointmentId
                                    }
                                });
                                if (status === 'confirmed') totalReservas++;
                                if (status === 'cancelled') totalCancelados++;
                                slotOcupado = true;
                            }
                        }
                    }
                }
            }
        }
        console.log(`✅ Seed completado:`);
        console.log(`   📅 Slots:       ${totalSlots}`);
        console.log(`   ✅ Confirmados: ${totalReservas}`);
        console.log(`   ❌ Cancelados:  ${totalCancelados}`);
        console.log(`   📊 Ocupación:   ${(totalReservas / totalSlots * 100).toFixed(1)}%`);
    })();


},
"./imports/api/analytics/analytics.publications.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var _appointments_appointments_js__rspack_import_1 = __webpack_require__("./imports/api/appointments/appointments.js");
/* import */ var _slots_slots_js__rspack_import_2 = __webpack_require__("./imports/api/slots/slots.js");



meteor_meteor__rspack_import_0.Meteor.publish('analytics.overview', function() {
    if (!this.userId) return this.ready();
    return [
        _appointments_appointments_js__rspack_import_1.Appointments.find({}, {
            fields: {
                barberId: 1,
                date: 1,
                hour: 1,
                status: 1
            }
        }),
        _slots_slots_js__rspack_import_2.Slots.find({}, {
            fields: {
                barberId: 1,
                date: 1,
                hour: 1,
                isAvailable: 1
            }
        })
    ];
});


},
"./imports/api/appointments/appointments.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  Appointments: () => (Appointments)
});
/* import */ var meteor_mongo__rspack_import_0 = __webpack_require__("meteor/mongo");
/* import */ var meteor_mongo__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_mongo__rspack_import_0);

const Appointments = new meteor_mongo__rspack_import_0.Mongo.Collection('appointments');


},
"./imports/api/appointments/appointments.methods.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_check__rspack_import_1 = __webpack_require__("meteor/check");
/* import */ var meteor_check__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_check__rspack_import_1);
/* import */ var _appointments_js__rspack_import_2 = __webpack_require__("./imports/api/appointments/appointments.js");
/* import */ var _slots_slots_js__rspack_import_3 = __webpack_require__("./imports/api/slots/slots.js");
/* import */ var _utils_constants_js__rspack_import_4 = __webpack_require__("./imports/utils/constants.js");
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}





meteor_meteor__rspack_import_0.Meteor.methods({
    'appointments.book' (_0) {
        return _async_to_generator(function*({ slotId, clientName, clientPhone }) {
            (0,meteor_check__rspack_import_1.check)(slotId, String);
            (0,meteor_check__rspack_import_1.check)(clientName, String);
            (0,meteor_check__rspack_import_1.check)(clientPhone, String);
            const slot = yield _slots_slots_js__rspack_import_3.Slots.findOneAsync({
                _id: slotId,
                isAvailable: true
            });
            if (!slot) throw new meteor_meteor__rspack_import_0.Meteor.Error('slot-unavailable', 'Este turno ya no está disponible');
            const appointmentId = yield _appointments_js__rspack_import_2.Appointments.insertAsync({
                slotId,
                clientName,
                clientPhone,
                barberId: slot.barberId,
                date: slot.date,
                hour: slot.hour,
                status: 'pending',
                createdAt: new Date()
            });
            yield _slots_slots_js__rspack_import_3.Slots.updateAsync(slotId, {
                $set: {
                    isAvailable: false,
                    appointmentId
                }
            });
            return appointmentId;
        }).apply(this, arguments);
    },
    'appointments.updateStatus' (_0) {
        return _async_to_generator(function*({ appointmentId, status }) {
            (0,meteor_check__rspack_import_1.check)(appointmentId, String);
            (0,meteor_check__rspack_import_1.check)(status, String);
            const validStatuses = Object.values(_utils_constants_js__rspack_import_4.APPOINTMENT_STATUS);
            if (!validStatuses.includes(status)) {
                throw new meteor_meteor__rspack_import_0.Meteor.Error('invalid-status', 'Estado inválido');
            }
            const appt = yield _appointments_js__rspack_import_2.Appointments.findOneAsync(appointmentId);
            if (!appt) throw new meteor_meteor__rspack_import_0.Meteor.Error('not-found', 'Turno no encontrado');
            if (this.userId !== appt.barberId) {
                throw new meteor_meteor__rspack_import_0.Meteor.Error('not-authorized', 'No tienes permiso');
            }
            yield _appointments_js__rspack_import_2.Appointments.updateAsync(appointmentId, {
                $set: {
                    status,
                    updatedAt: new Date()
                }
            });
            if (status === _utils_constants_js__rspack_import_4.APPOINTMENT_STATUS.CANCELLED) {
                yield _slots_slots_js__rspack_import_3.Slots.updateAsync(appt.slotId, {
                    $set: {
                        isAvailable: true,
                        appointmentId: null
                    }
                });
            }
        }).apply(this, arguments);
    },
    'appointments.cancel' (_0) {
        return _async_to_generator(function*({ appointmentId }) {
            (0,meteor_check__rspack_import_1.check)(appointmentId, String);
            const appt = yield _appointments_js__rspack_import_2.Appointments.findOneAsync(appointmentId);
            if (!appt) throw new meteor_meteor__rspack_import_0.Meteor.Error('not-found', 'Turno no encontrado');
            yield _appointments_js__rspack_import_2.Appointments.updateAsync(appointmentId, {
                $set: {
                    status: _utils_constants_js__rspack_import_4.APPOINTMENT_STATUS.CANCELLED,
                    cancelledAt: new Date()
                }
            });
            yield _slots_slots_js__rspack_import_3.Slots.updateAsync(appt.slotId, {
                $set: {
                    isAvailable: true,
                    appointmentId: null
                }
            });
        }).apply(this, arguments);
    }
});


},
"./imports/api/appointments/appointments.publications.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_check__rspack_import_1 = __webpack_require__("meteor/check");
/* import */ var meteor_check__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_check__rspack_import_1);
/* import */ var _appointments_js__rspack_import_2 = __webpack_require__("./imports/api/appointments/appointments.js");



meteor_meteor__rspack_import_0.Meteor.publish('appointments.myBarber', function() {
    if (!this.userId) return this.ready();
    return _appointments_js__rspack_import_2.Appointments.find({
        barberId: this.userId,
        status: {
            $ne: 'cancelled'
        }
    }, {
        sort: {
            date: 1,
            hour: 1
        }
    });
});
meteor_meteor__rspack_import_0.Meteor.publish('appointments.today', function() {
    if (!this.userId) return this.ready();
    const start = new Date();
    start.setUTCHours(5, 0, 0, 0);
    const end = new Date();
    end.setUTCHours(28, 59, 59, 999);
    return _appointments_js__rspack_import_2.Appointments.find({
        barberId: this.userId,
        date: {
            $gte: start,
            $lte: end
        }
    });
});
meteor_meteor__rspack_import_0.Meteor.publish('appointments.all', function() {
    if (!this.userId) return this.ready();
    return _appointments_js__rspack_import_2.Appointments.find({}, {
        sort: {
            date: -1
        }
    });
});


},
"./imports/api/predictions/predictions.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  Predictions: () => (Predictions)
});
/* import */ var meteor_mongo__rspack_import_0 = __webpack_require__("meteor/mongo");
/* import */ var meteor_mongo__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_mongo__rspack_import_0);

const Predictions = new meteor_mongo__rspack_import_0.Mongo.Collection('predictions'); // {
 //   _id: String,
 //   diaSemana: Number,        // 1=lun, 2=mar... 6=sab
 //   hora: String,             // '09:00'
 //   clientesEsperados: Number, // promedio histórico
 //   barberosRecomendados: Number,
 //   ocupacionHistorica: Number, // % promedio
 //   alerta: String,           // 'ok' | 'overbooking' | 'sobrecapacidad' | 'demanda_alta'
 //   semanasTomadas: Number,   // cuántas semanas de datos se usaron
 //   updatedAt: Date,
 // }


},
"./imports/api/predictions/predictions.methods.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  calcularPredicciones: () => (calcularPredicciones)
});
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var _appointments_appointments_js__rspack_import_1 = __webpack_require__("./imports/api/appointments/appointments.js");
/* import */ var _predictions_js__rspack_import_2 = __webpack_require__("./imports/api/predictions/predictions.js");
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}



const HORAS = [
    '09:00',
    '10:00',
    '11:00',
    '12:00',
    '14:00',
    '15:00',
    '16:00',
    '17:00'
];
const DIAS = [
    1,
    2,
    3,
    4,
    5,
    6
];
const detectarAlerta = (clientesEsperados, barberosRecomendados, ocupacion)=>{
    if (ocupacion > 0.85) return 'demanda_alta';
    if (clientesEsperados > barberosRecomendados) return 'overbooking';
    if (barberosRecomendados > 3 && clientesEsperados < barberosRecomendados * 0.4) return 'sobrecapacidad';
    return 'ok';
};
const calcularPredicciones = ()=>_async_to_generator(function*() {
        console.log('🔮 Calculando predicciones...');
        const appointments = yield _appointments_appointments_js__rspack_import_1.Appointments.find({
            status: {
                $in: [
                    'confirmed',
                    'cancelled'
                ]
            }
        }).fetchAsync();
        const semanasUnicas = new Set(appointments.map((a)=>{
            const d = new Date(a.date);
            return Math.floor(d.getTime() / (7 * 24 * 60 * 60 * 1000));
        }));
        const totalSemanas = Math.max(semanasUnicas.size, 1);
        const predicciones = [];
        for (const diaSemana of DIAS){
            for (const hora of HORAS){
                const apptsDiaHora = appointments.filter((a)=>{
                    const d = new Date(a.date);
                    return d.getDay() === diaSemana && a.hour === hora;
                });
                const confirmados = apptsDiaHora.filter((a)=>a.status === 'confirmed').length;
                const cancelados = apptsDiaHora.filter((a)=>a.status === 'cancelled').length;
                const total = confirmados + cancelados;
                const clientesEsperados = parseFloat((confirmados / totalSemanas).toFixed(2));
                const barberosRecomendados = Math.max(Math.ceil(clientesEsperados), 1);
                const ocupacionHistorica = total > 0 ? parseFloat((confirmados / total).toFixed(2)) : 0;
                const alerta = detectarAlerta(clientesEsperados, barberosRecomendados, ocupacionHistorica);
                predicciones.push({
                    diaSemana,
                    hora,
                    clientesEsperados,
                    barberosRecomendados,
                    ocupacionHistorica,
                    alerta,
                    semanasTomadas: totalSemanas,
                    updatedAt: new Date()
                });
            }
        }
        yield _predictions_js__rspack_import_2.Predictions.removeAsync({});
        for (const pred of predicciones){
            yield _predictions_js__rspack_import_2.Predictions.insertAsync(pred);
        }
        console.log(`✅ ${predicciones.length} predicciones calculadas`);
        return predicciones.length;
    })();
meteor_meteor__rspack_import_0.Meteor.methods({
    'predictions.calculate' () {
        return _async_to_generator(function*() {
            if (!this.userId) throw new meteor_meteor__rspack_import_0.Meteor.Error('not-logged-in');
            return yield calcularPredicciones();
        }).call(this);
    }
});


},
"./imports/api/predictions/predictions.publications.js"() {


},
"./imports/api/slots/slots.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  Slots: () => (Slots)
});
/* import */ var meteor_mongo__rspack_import_0 = __webpack_require__("meteor/mongo");
/* import */ var meteor_mongo__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_mongo__rspack_import_0);

const Slots = new meteor_mongo__rspack_import_0.Mongo.Collection('slots');


},
"./imports/api/slots/slots.methods.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_check__rspack_import_1 = __webpack_require__("meteor/check");
/* import */ var meteor_check__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_check__rspack_import_1);
/* import */ var _slots_js__rspack_import_2 = __webpack_require__("./imports/api/slots/slots.js");
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}



meteor_meteor__rspack_import_0.Meteor.methods({
    'slots.generateForDay' (_0) {
        return _async_to_generator(function*({ date, hours }) {
            (0,meteor_check__rspack_import_1.check)(date, Date);
            (0,meteor_check__rspack_import_1.check)(hours, [
                String
            ]);
            if (!this.userId) throw new meteor_meteor__rspack_import_0.Meteor.Error('not-logged-in', 'Debes iniciar sesión');
            yield _slots_js__rspack_import_2.Slots.removeAsync({
                barberId: this.userId,
                date,
                isAvailable: true
            });
            for (const hour of hours){
                yield _slots_js__rspack_import_2.Slots.insertAsync({
                    barberId: this.userId,
                    date,
                    hour,
                    isAvailable: true,
                    appointmentId: null,
                    createdAt: new Date()
                });
            }
        }).apply(this, arguments);
    }
});


},
"./imports/api/slots/slots.publications.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_check__rspack_import_1 = __webpack_require__("meteor/check");
/* import */ var meteor_check__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_check__rspack_import_1);
/* import */ var _slots_js__rspack_import_2 = __webpack_require__("./imports/api/slots/slots.js");



meteor_meteor__rspack_import_0.Meteor.publish('slots.available', function({ date }) {
    (0,meteor_check__rspack_import_1.check)(date, Date);
    // Usar rango del día completo en vez de igualdad exacta
    // para evitar problemas de milisegundos en comparación de fechas
    const start = new Date(date);
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(date);
    end.setUTCHours(23, 59, 59, 999);
    return _slots_js__rspack_import_2.Slots.find({
        date: {
            $gte: start,
            $lte: end
        },
        isAvailable: true
    });
});
meteor_meteor__rspack_import_0.Meteor.publish('slots.myDay', function({ date }) {
    (0,meteor_check__rspack_import_1.check)(date, Date);
    if (!this.userId) return this.ready();
    const start = new Date(date);
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(date);
    end.setUTCHours(23, 59, 59, 999);
    return _slots_js__rspack_import_2.Slots.find({
        barberId: this.userId,
        date: {
            $gte: start,
            $lte: end
        }
    });
});


},
"./imports/api/users/users.methods.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_accounts_base__rspack_import_1 = __webpack_require__("meteor/accounts-base");
/* import */ var meteor_accounts_base__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_accounts_base__rspack_import_1);
/* import */ var meteor_check__rspack_import_2 = __webpack_require__("meteor/check");
/* import */ var meteor_check__rspack_import_2_default = /*#__PURE__*/__webpack_require__.n(meteor_check__rspack_import_2);



meteor_meteor__rspack_import_0.Meteor.methods({
    'users.register' ({ name, email, password, role }) {
        (0,meteor_check__rspack_import_2.check)(name, String);
        (0,meteor_check__rspack_import_2.check)(email, String);
        (0,meteor_check__rspack_import_2.check)(password, String);
        (0,meteor_check__rspack_import_2.check)(role, String);
        const userId = meteor_accounts_base__rspack_import_1.Accounts.createUser({
            email,
            password,
            profile: {
                name,
                role
            }
        });
        return userId;
    }
});


},
"./imports/startup/server/accounts.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_accounts_base__rspack_import_0 = __webpack_require__("meteor/accounts-base");
/* import */ var meteor_accounts_base__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_accounts_base__rspack_import_0);

meteor_accounts_base__rspack_import_0.Accounts.validateNewUser((user)=>{
    var _user_profile;
    const role = (_user_profile = user.profile) === null || _user_profile === void 0 ? void 0 : _user_profile.role;
    if (!role || ![
        'barbero',
        'cliente'
    ].includes(role)) {
        throw new Meteor.Error('invalid-role', 'Rol inválido');
    }
    return true;
});
meteor_accounts_base__rspack_import_0.Accounts.onCreateUser((options, user)=>{
    var _options_profile, _options_profile1;
    user.profile = {
        name: ((_options_profile = options.profile) === null || _options_profile === void 0 ? void 0 : _options_profile.name) || '',
        role: ((_options_profile1 = options.profile) === null || _options_profile1 === void 0 ? void 0 : _options_profile1.role) || 'cliente',
        createdAt: new Date()
    };
    return user;
});


},
"./imports/utils/constants.js"(__unused_rspack_module, __webpack_exports__, __webpack_require__) {
"use strict";
__webpack_require__.d(__webpack_exports__, {
  APPOINTMENT_STATUS: () => (APPOINTMENT_STATUS)
});
const ROLES = {
    BARBERO: 'barbero',
    CLIENTE: 'cliente'
};
const ROUTES = {
    LOGIN: '/login',
    REGISTER: '/register',
    DASHBOARD: '/dashboard',
    BOOKING: '/booking'
};
const APPOINTMENT_STATUS = {
    PENDING: 'pending',
    CONFIRMED: 'confirmed',
    CANCELLED: 'cancelled'
};


},
"./server/main.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
"use strict";
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_accounts_base__rspack_import_1 = __webpack_require__("meteor/accounts-base");
/* import */ var meteor_accounts_base__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_accounts_base__rspack_import_1);
/* import */ var _imports_api_appointments_appointments_js__rspack_import_2 = __webpack_require__("./imports/api/appointments/appointments.js");
/* import */ var _imports_api_predictions_predictions_js__rspack_import_3 = __webpack_require__("./imports/api/predictions/predictions.js");
/* import */ var _imports_api_appointments_appointments_methods_js__rspack_import_4 = __webpack_require__("./imports/api/appointments/appointments.methods.js");
/* import */ var _imports_api_appointments_appointments_publications_js__rspack_import_5 = __webpack_require__("./imports/api/appointments/appointments.publications.js");
/* import */ var _imports_api_slots_slots_methods_js__rspack_import_6 = __webpack_require__("./imports/api/slots/slots.methods.js");
/* import */ var _imports_api_slots_slots_publications_js__rspack_import_7 = __webpack_require__("./imports/api/slots/slots.publications.js");
/* import */ var _imports_startup_server_accounts_js__rspack_import_8 = __webpack_require__("./imports/startup/server/accounts.js");
/* import */ var _imports_api_users_users_methods_js__rspack_import_9 = __webpack_require__("./imports/api/users/users.methods.js");
/* import */ var _imports_api_analytics_analytics_publications_js__rspack_import_10 = __webpack_require__("./imports/api/analytics/analytics.publications.js");
/* import */ var _imports_api_predictions_predictions_methods_js__rspack_import_11 = __webpack_require__("./imports/api/predictions/predictions.methods.js");
/* import */ var _imports_api_predictions_predictions_publications_js__rspack_import_12 = __webpack_require__("./imports/api/predictions/predictions.publications.js");
/* import */ var _imports_api_predictions_predictions_publications_js__rspack_import_12_default = /*#__PURE__*/__webpack_require__.n(_imports_api_predictions_predictions_publications_js__rspack_import_12);
/* import */ var _bot_seed_js__rspack_import_13 = __webpack_require__("./bot/seed.js");
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}















meteor_meteor__rspack_import_0.Meteor.startup(()=>_async_to_generator(function*() {
        const count = yield meteor_meteor__rspack_import_0.Meteor.users.find().countAsync();
        if (count === 0) {
            yield meteor_accounts_base__rspack_import_1.Accounts.createUser({
                email: 'barbero@demo.com',
                password: '123456',
                profile: {
                    name: 'Carlos el Barbero',
                    role: 'barbero'
                }
            });
        }
        const totalAppointments = yield _imports_api_appointments_appointments_js__rspack_import_2.Appointments.find().countAsync();
        if (totalAppointments < 50) {
            console.log('📊 Iniciando generación de datos históricos...');
            yield (0,_bot_seed_js__rspack_import_13.runSeed)();
        }
        const totalPreds = yield _imports_api_predictions_predictions_js__rspack_import_3.Predictions.find().countAsync();
        if (totalPreds === 0) {
            console.log('🔮 Calculando predicciones iniciales...');
            yield (0,_imports_api_predictions_predictions_methods_js__rspack_import_11.calcularPredicciones)();
        }
    })());


},
"meteor/accounts-base"(module) {
"use strict";
module.exports = require("meteor/accounts-base");

},
"meteor/check"(module) {
"use strict";
module.exports = require("meteor/check");

},
"meteor/meteor"(module) {
"use strict";
module.exports = require("meteor/meteor");

},
"meteor/mongo"(module) {
"use strict";
module.exports = require("meteor/mongo");

},

});
// The module cache
var __webpack_module_cache__ = {};

// The require function
function __webpack_require__(moduleId) {

// Check if module is in cache
var cachedModule = __webpack_module_cache__[moduleId];
if (cachedModule !== undefined) {
return cachedModule.exports;
}
// Create a new module (and put it into the cache)
var module = (__webpack_module_cache__[moduleId] = {
exports: {}
});
// Execute the module function
__webpack_modules__[moduleId](module, module.exports, __webpack_require__);

// Return the exports of the module
return module.exports;

}

// webpack/runtime/compat_get_default_export
(() => {
// getDefaultExport function for compatibility with non-ESM modules
__webpack_require__.n = (module) => {
	var getter = module && module.__esModule ?
		() => (module['default']) :
		() => (module);
	__webpack_require__.d(getter, { a: getter });
	return getter;
};

})();
// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, definition) => {
	for(var key in definition) {
        if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
            Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
        }
    }
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// This entry needs to be wrapped in an IIFE because it needs to be in strict mode.
(() => {
"use strict";
__webpack_require__.r(__webpack_exports__);
/* import */ var _server_main_js__rspack_import_0 = __webpack_require__("./server/main.js");
/**
* @file server-entry.js
* @description Entry point for Rspack build process
* --------------------------------------------------------------------------
* 🔌 Rspack Server Entry (Development)
* --------------------------------------------------------------------------
* • [■ server-entry.js ] ──▶ [   server-rspack.js ] ──▶ [   server-meteor.js ]
*
* This file is the entry point that Rspack uses to start the build process.
* It imports the module defined in `meteor.mainModule.server` inside package.json.
* From here, Rspack can trace the entire dependency graph of your application
* and generate the bundled output (`server-rspack.js`).
*
* ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
* These files also act as a cache: they can be safely removed and will be
* regenerated on the next build. They should be ignored in IDE suggestions
* and version control.
*/ /* Link to 🔌 Meteor Server Entry */ 

})();

module.exports = __webpack_exports__;
})()
;
//# sourceMappingURL=server-rspack.js.map