/**
* @file test-entry.js
* @description No code generated
* --------------------------------------------------------------------------
* ⚡ Rspack Test Test Entry (Test)
* --------------------------------------------------------------------------
* • [■ test-entry.js ] ──▶ [   test-rspack.js ] ──▶ [   test-meteor.js ]
*
* This file is empty because `meteor.testModule` is not set in package.json.
*
* ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
* These files also act as a cache: they can be safely removed and will be
* regenerated on the next build. They should be ignored in IDE suggestions
* and version control.
*/



